name: graphrag
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.2.1=py311haa95532_0
  - debugpy=1.8.16=py311h885b0b7_1
  - decorator=5.2.1=py311haa95532_0
  - executing=2.2.1=py311haa95532_0
  - expat=2.7.3=h9214b88_0
  - ipykernel=6.30.1=py311haa95532_0
  - ipython=9.5.0=py311haa95532_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - jupyter_client=8.6.3=py311haa95532_0
  - jupyter_core=5.8.1=py311haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.1.7=py311haa95532_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py311haa95532_1
  - parso=0.8.4=py311haa95532_0
  - platformdirs=4.5.0=py311haa95532_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311h02ab6af_1
  - pure_eval=0.2.3=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - pywin32=311=py311h885b0b7_0
  - pyzmq=27.1.0=py311h7149c55_1
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py311h827c3e9_0
  - traitlets=5.14.3=py311haa95532_0
  - typing_extensions=4.15.0=py311haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py311haa95532_0
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiolimiter==1.2.1
      - aiosignal==1.4.0
      - alembic==1.17.2
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - anyio==4.11.0
      - anytree==2.13.0
      - asttokens==2.4.1
      - attrs==25.4.0
      - autogen-agentchat==0.7.5
      - autogen-core==0.7.5
      - autogenstudio==0.4.2.2
      - autograd==1.8.0
      - azure-ai-documentintelligence==1.0.2
      - azure-ai-inference==1.0.0b9
      - azure-ai-projects==2.0.0b2
      - azure-common==1.1.28
      - azure-core==1.36.0
      - azure-cosmos==4.14.1
      - azure-identity==1.25.1
      - azure-search-documents==11.6.0
      - azure-storage-blob==12.27.1
      - beartype==0.18.5
      - beautifulsoup4==4.14.3
      - blis==1.3.0
      - brotli==1.2.0
      - catalogue==2.0.10
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpathlib==0.23.0
      - cobble==0.1.4
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - cymem==2.0.11
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - devtools==0.12.2
      - distro==1.9.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - email-validator==2.3.0
      - environs==14.5.0
      - et-xmlfile==2.0.0
      - fastapi==0.121.0
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fastuuid==0.14.0
      - ffmpy==0.6.4
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fnllm==0.4.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - future==1.0.0
      - gensim==4.4.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - graphrag==2.7.0
      - graspologic==3.4.4
      - graspologic-native==1.2.5
      - greenlet==3.2.4
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - html2text==2025.4.15
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.1.2
      - humanfriendly==10.0
      - hyppo==0.5.2
      - idna==3.11
      - importlib-metadata==8.7.0
      - isodate==0.7.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - json-repair==0.52.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lance-namespace==0.0.20
      - lance-namespace-urllib3-client==0.0.20
      - lancedb==0.25.2
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.7
      - langchain-ollama==1.0.0
      - langchain-openai==1.0.3
      - langchain-text-splitters==1.0.0
      - langcodes==3.5.0
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.43
      - language-data==1.3.0
      - litellm==1.79.1
      - llvmlite==0.45.1
      - loguru==0.7.3
      - lxml==6.0.2
      - magika==0.6.3
      - mako==1.3.10
      - mammoth==1.11.0
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markdownify==1.2.2
      - markitdown==0.1.4
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - multidict==6.7.0
      - murmurhash==1.0.13
      - mypy-extensions==1.1.0
      - neo4j==6.0.3
      - networkx==3.5
      - nltk==3.9.1
      - numba==0.62.1
      - numpy==1.26.4
      - olefile==0.47
      - ollama==0.6.1
      - onnxruntime==1.20.1
      - openai==2.7.1
      - openpyxl==3.1.5
      - opentelemetry-api==1.39.0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - overrides==7.7.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pdfminer-six==20251107
      - pillow==11.3.0
      - pip==25.3
      - playwright==1.56.0
      - pot==0.9.6.post1
      - preshed==3.0.10
      - propcache==0.4.1
      - protobuf==5.29.5
      - psycopg==3.3.1
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pyee==13.0.0
      - pyjwt==2.10.1
      - pylance==0.39.0
      - pymupdf==1.26.6
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pyreadline3==3.5.4
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - rpds-py==0.28.0
      - ruff==0.14.4
      - safehttpx==0.1.7
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - smart-open==7.4.4
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - speechrecognition==3.14.4
      - sqlalchemy==2.0.44
      - sqlmodel==0.0.27
      - srsly==2.5.1
      - starlette==0.49.3
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - textblob==0.19.0
      - thinc==8.3.7
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wasabi==1.1.3
      - watchfiles==1.1.1
      - weasel==0.4.2
      - websockets==15.0.1
      - win32-setctime==1.2.0
      - wrapt==2.0.0
      - xlrd==2.0.2
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
      - youtube-transcript-api==1.0.3
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: C:\Users\User\anaconda3\envs\graphrag
